### ISSUE TITLE
Correct Font Size for Scaling

### ISSUE THREAD

**Issue by rteeling** [lalo/VT220-mod-font#1]
The font doesn't scale correctly at most sizes. It looks right with the following sizes on the following OSes

OS | Correct Size
----|-------------
Windows 10 | 19
OSX | 20
Linux | 15

**Comment by davelang68** [comment]
Is there a way to fix / change that? I love the font, but would like to use a larger size than 15 on my linux install...

**Comment by lalo** [comment]
How does one fix this? I'm not an expert on font making :)

**Comment by lalo** [comment]
How does one fix this? I'm not an expert on font making :)

**Comment by rteeling** [comment]
Just wanted to document the right size on the readme. Sent you a PR
